name: Waka Readme v2

on:
  # for manual workflow trigger
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "30 18 * * *"
  workflow_dispatch:
  

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
        # this action name
      - uses: anmol098/waka-readme-stats@master # do NOT replace with anything else
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA_SECRET_API }} # required
          GH_TOKEN: ${{ secrets.MY_GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          SHOW_OS: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "False"
          SYMBOL_VERSION: "2"
          DEBUG_LOGGING: "False"
          # you can populate email-id with secretes instead
