name: Waka Readme

on:
  # for manual workflow trigger
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "30 18 * * *"
  workflow_dispatch:
  

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
        # this action name
      - uses: anmol098/waka-readme-stats@master # do NOT replace with anything else
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA_SECRET_API }} # required
          GH_TOKEN: ${{ secrets.MY_GH_TOKEN }}
          INPUT_LOCALE: "True"
          # you can populate email-id with secretes instead
